on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
      - name: Install pre-commit
        run: pip install pre-commit
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
      - run: pre-commit --all-files --show-diff-on-failure
